SAVVA_DZHUMALIEV Tasks 1-10
EasileleM/ui-internship-lwo2 pull request #1
Opened 2019-09-09 20:04 UTC by EasileleM

2019-09-10 14:22 UTC, vovcyan requested changes

2019-09-10 14:22 UTC, vovcyan commented on tasks/10_remove-whitespaces/remove-whitespaces.js
> +  return str.replace(RegExp(' ', 'g'), '');
Split it by separate lines

2019-09-10 14:22 UTC, vovcyan commented on tasks/1_golf-score/golf-score.js
> +  if (strokes===1) return 'Hole-in-one!';
if (strokes === 1)

2019-09-10 14:22 UTC, vovcyan commented on tasks/1_golf-score/golf-score.js
> +export const GOLF_SCORES={
export const GOLF_SCORES = {

2019-09-10 14:22 UTC, vovcyan commented on tasks/2_convert-to-f/convert-to-f.js
> +  return celsius*1.8+32;
Please add whitespaces in your code and after that ping me for review

2019-09-10 19:12 UTC, vadeneev requested changes

2019-09-10 19:12 UTC, vadeneev commented on tasks/2_convert-to-f/convert-to-f.js
> +  return celsius * 1.8 + 32;
26*1.8 + 32 = 78.80000000000001 :(

2019-09-10 19:12 UTC, vadeneev commented on tasks/3_is-boolean/is-boolean.js
> +  return bool===true||bool===false;
I suggest to read more about checking types in JS

2019-09-10 19:12 UTC, vadeneev commented on tasks/9_find-numbers/find-numbers.js
> +  for (let i = 0; i<arr.length; i++) arr[i]=+arr[i];
Is there any other ways to cast any type to Number ? How about documentation ? for example https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number i'm not talking about YDKJS series

2019-09-10 19:18 UTC, EasileleM commented on tasks/2_convert-to-f/convert-to-f.js
> +  return celsius * 1.8 + 32;
What precision should i set then? :D

2019-09-11 05:57 UTC, vovcyan requested changes

2019-09-11 05:57 UTC, vovcyan commented on tasks/10_remove-whitespaces/remove-whitespaces.js
> +      .replace(
Please make it in the 1 line

2019-09-11 05:57 UTC, vovcyan commented on tasks/5_profile-lookup/profile-lookup.js
> +let contacts = [
const

2019-09-11 05:57 UTC, vovcyan commented on tasks/1_golf-score/golf-score.js
> +  if (strokes === 1) return 'Hole-in-one!';
Please refactor it in all your code:

if (strokes === 1) { 
   return 'Hole-in-one!';
}

2019-09-11 07:46 UTC, akimovaa submitted a review, later dismissed

2019-09-11 07:46 UTC, akimovaa commented on tasks/3_is-boolean/is-boolean.js
> +    return bool===true||bool===false;
What's happened if we trying to work with Boolean as an Object? new Boolean(true) for example. Just for FYI. Do you know smth about typeof or other type checkings?

2019-09-11 07:46 UTC, akimovaa commented on tasks/5_profile-lookup/profile-lookup.js
> +var contacts = [
Use const instead var. Just FYI.

2019-09-11 07:46 UTC, akimovaa commented on tasks/5_profile-lookup/profile-lookup.js
> +export function lookupProfile(firstName, prop){
If we have two objects with the same firstName - what's happened?

2019-09-11 07:46 UTC, akimovaa commented on tasks/5_profile-lookup/profile-lookup.js
> +    for(let contact of contacts){
Why do you work with array <code>contracts</code> like with object? Use .forEach().

2019-09-11 07:46 UTC, akimovaa commented on tasks/7_random-fraction/random-fraction.js
> +    return Math.random();
Decimal means at this case 0.1, 0.2, 0.3 ... 0,9

2019-09-11 07:46 UTC, akimovaa commented on tasks/8_factorize-number/factorize-number.js
> +    for(let i = 1; i<=n;i++) result*=i;
You don't need to use iteration. There you can find out more concise one-line solution.

2019-09-11 07:46 UTC, akimovaa commented on tasks/9_find-numbers/find-numbers.js
> +    for(let i = 0; i<arr.length;i++) arr[i]=+arr[i];
You don't need to use <code>for</code>. You can iterate and map <code>arr</code> at the previous line

2019-09-11 07:46 UTC, akimovaa commented on tasks/10_remove-whitespaces/remove-whitespaces.js
> +    return str.replace(RegExp(' ','g'), '');
<code>str.replace(/ /g, '')</code>

2019-09-11 07:54 UTC, savchukm requested changes

2019-09-11 07:54 UTC, savchukm commented on tasks/1_golf-score/golf-score.js
> +  if (strokes <= par-2) {
Please add spaces around binary operators.
Example: 
`strokes <= par - 2`

2019-09-11 07:54 UTC, savchukm commented on tasks/1_golf-score/golf-score.js
> +    return 'Hole-in-one!';
I think you should return that constant value `GOLF_SCORES.something `

2019-09-11 08:59 UTC, EasileleM commented on tasks/5_profile-lookup/profile-lookup.js
> +export function lookupProfile(firstName, prop){
Only property of the first object with firstName will be returned

2019-09-12 06:49 UTC, alexkond requested changes

2019-09-12 06:49 UTC, alexkond commented on tasks/1_golf-score/golf-score.js
> +  if (strokes === 1) {
Consider using `switch` in such cases.

2019-09-12 06:49 UTC, alexkond commented on tasks/5_profile-lookup/profile-lookup.js
> +  if (contact === undefined) {
It could be shortened to `if (!contact)`.

2019-09-12 06:49 UTC, alexkond commented on tasks/8_factorize-number/factorize-number.spec.js
> -// import { factorialize } from './factorize-number';
Does this file committed intentionally or by mistake?

2019-09-12 08:10 UTC, akimovaa approved these changes

2019-09-12 08:21 UTC, vovcyan approved these changes

2019-09-12 08:21 UTC, vovcyan commented on tasks/10_remove-whitespaces/remove-whitespaces.js
> +      .replace(/ /g, '');
Why do you need to move to new line? Remove \n pls

2019-09-12 08:28 UTC, alexkond approved these changes

2019-09-12 08:49 UTC, merged