Savva Dzhumaliev Tasks 91-100
EasileleM/ui-internship-lwo2 pull request #13
Opened 2019-09-22 11:46 UTC by EasileleM

2019-09-23 07:00 UTC, vovcyan requested changes

2019-09-23 07:00 UTC, vovcyan commented on tasks/91_make-a-person/make-a-person.js
> +    let firstName = fullNameSplit[0];
Please use ES6 feature for it

2019-09-23 07:00 UTC, vovcyan commented on tasks/92_calculate-orbital-period/calculate-orbital-period.js
> +    body['orbitalPeriod'] = Math.round(2 * PI * Math.sqrt(Math.pow(body.avgAlt
Please split line

2019-09-23 07:00 UTC, vovcyan commented on tasks/92_calculate-orbital-period/calculate-orbital-period.js
> +    body['orbitalPeriod'] = Math.round(2 * PI * Math.sqrt(Math.pow(body.avgAlt
body.orbitalPeriod ?

2019-09-23 10:44 UTC, akimovaa approved these changes

2019-09-23 10:44 UTC, akimovaa commented on tasks/96_greatest-common-divisor/greatest-common-divisor.js
> +export function greatestCommonDivisor(a, b) {
The best solution! Congrats.

2019-09-24 07:23 UTC, vovcyan approved these changes

2019-09-24 10:18 UTC, merged