Savva dzhumaliev 21 30
EasileleM/ui-internship-lwo2 pull request #3
Opened 2019-09-11 21:51 UTC by EasileleM

2019-09-12 09:27 UTC, akimovaa submitted a review, later dismissed

2019-09-12 10:04 UTC, akimovaa submitted a review, later dismissed

2019-09-12 13:04 UTC, akimovaa submitted a review, later dismissed

2019-09-13 05:29 UTC, alexkond requested changes

2019-09-13 05:29 UTC, alexkond commented on tasks/10_remove-whitespaces/remove-whitespaces.js
> +export function trimWhiteSpaces(str) {
Why PR for tasks 21-30 has changes for files, not related to these tasks?

2019-09-13 06:52 UTC, akimovaa approved these changes

2019-09-13 07:23 UTC, alexkond approved these changes

2019-09-13 07:27 UTC, vadeneev approved these changes

2019-09-13 08:05 UTC, merged