Savva Dzhumaliev Tasks 31-40
EasileleM/ui-internship-lwo2 pull request #4
Opened 2019-09-12 19:21 UTC by EasileleM

2019-09-13 05:42 UTC, alexkond requested changes

2019-09-13 05:42 UTC, alexkond commented on tasks/34_max-triplet-sum/max-triplet-sum.js
> +    const tempMax = Math.max(...arr);
Does this value changes while you iterate?

2019-09-13 05:42 UTC, alexkond commented on tasks/35_array-leaders/array-leaders.js
> +    if (arr[i] > sum) result.push(arr[i]);
Please, don't use `if` without curly braces.

2019-09-13 05:42 UTC, alexkond commented on tasks/36_row-weight/row-weight.js
> +    if (index%2) {
Minor, please add spaces around `%` operator

2019-09-13 05:42 UTC, alexkond commented on tasks/38_max-product/max-product.js
> +    result = Math.max(result, arr[i]*arr[i+1]);
Minor, spaces around `*` and `+`

2019-09-13 06:18 UTC, EasileleM commented on tasks/34_max-triplet-sum/max-triplet-sum.js
> +    const tempMax = Math.max(...arr);
Yes, i sum it with a max array number each loop iteration.

2019-09-13 07:54 UTC, vadeneev requested changes

2019-09-13 07:54 UTC, vadeneev commented on tasks/32_numbers-to-reversed-array/numbers-to-reversed-array.js
> +      .map((value) => Number(value));
Number is a function, so we could use it just .map(Number)

2019-09-13 07:54 UTC, vadeneev commented on tasks/33_array-plus-array/array-plus-array.js
> +    result.push((arr1[i] ? arr1[i] : 0) + (arr2[i] ? arr2[i] : 0));
Too much ternaries for one line, isn't it ? arr1[i] || 0 + arr2[i] || 0

2019-09-13 07:54 UTC, vadeneev commented on tasks/33_array-plus-array/array-plus-array.js
> +  for (let i = 0; i < arr1.length || i < arr2.length; i++) {
let's use pre-calculated value here

2019-09-13 07:54 UTC, vadeneev commented on tasks/34_max-triplet-sum/max-triplet-sum.js
> +    arr = arr.filter((value) => value !== tempMax);
Why do we still mutating initial array ?

2019-09-13 07:54 UTC, vadeneev commented on tasks/35_array-leaders/array-leaders.js
> +  for (let i = arr.length - 1, sum = 0; i >= 0; sum += arr[i], i--) {
> “Good code is written so that is readable, understandable, covered by automated tests, not over complicated and does well what is intended to do.”

I want to say, such conditions is not easy to read in one flow - perhaps, it is a habit question, however you should assume that developers of different levels should be able easily support this code, otherwise you will need mental shield to protect your karma ;)

2019-09-13 07:54 UTC, vadeneev commented on tasks/37_min-number-to-prime/min-number-to-prime.js
> +  const isPrime = (num) => {
I can't see any reason ti keep this function inside parent

2019-09-13 08:16 UTC, EasileleM commented on tasks/34_max-triplet-sum/max-triplet-sum.js
> +    arr = arr.filter((value) => value !== tempMax);
![Screen Shot 2019-09-13 at 12 13 31 PM](https://user-images.githubusercontent.com/49760922/64847400-f983b780-d61f-11e9-83a6-90b49c498648.png)
We doesn't. Function changes only reference to the initial array (namely - arr).

2019-09-13 08:38 UTC, EasileleM commented on tasks/34_max-triplet-sum/max-triplet-sum.js
> +    arr = arr.filter((value) => value !== tempMax);
![Screen Shot 2019-09-13 at 12 13 31 PM](https://user-images.githubusercontent.com/49760922/64848910-474def00-d623-11e9-9d72-d6b725848ef3.png)
If i'm not wrong, this function doesn't mutate initial array. Filter always creates a new array and changes only 'arr' reference.

2019-09-16 08:19 UTC, akimovaa submitted a review, later dismissed

2019-09-16 18:42 UTC, akimovaa approved these changes

2019-09-17 05:48 UTC, KalachevDev approved these changes

2019-09-17 05:48 UTC, KalachevDev commented on tasks/33_array-plus-array/array-plus-array.js
> +  for (let i = 0; i < len1 || i < len2; i++) {
You could use Math.max here to compute the biggest value once

2019-09-17 05:56 UTC, merged