Savva Dzhumaliev Tasks 41-50
EasileleM/ui-internship-lwo2 pull request #5
Opened 2019-09-15 12:24 UTC by EasileleM

2019-09-16 08:02 UTC, vovcyan requested changes

2019-09-16 08:02 UTC, vovcyan commented on tasks/41_sort-by-bits/sort-by-bits.js
> +    let bitsA = countBits(a);
const

2019-09-16 08:02 UTC, vovcyan commented on tasks/42_first-n-smallest/first-n-smallest.js
> +  let arrCloneRev = Array(...arr).reverse();
const

2019-09-16 08:02 UTC, vovcyan commented on tasks/45_equal-sides/equal-sides.js
> +  let sumRight = arr.reduce((sum, value) => sum + value, 0);
const

2019-09-16 08:11 UTC, EasileleM commented on tasks/45_equal-sides/equal-sides.js
> +  let sumRight = arr.reduce((sum, value) => sum + value, 0);
This variable changes through execution

2019-09-16 14:30 UTC, akimovaa requested changes

2019-09-16 14:30 UTC, akimovaa commented on tasks/47_string-expansion/string-expansion.js
> +export function stringExpansion(str) {
You can find solution with only one loop, w/o too many operations.

2019-09-16 15:09 UTC, akimovaa approved these changes

2019-09-17 06:16 UTC, KalachevDev approved these changes

2019-09-17 06:16 UTC, KalachevDev commented on tasks/41_sort-by-bits/sort-by-bits.js
> +    if (a & (1 << i)) {
oh my lord, it is computer science stuff here!

2019-09-17 06:20 UTC, KalachevDev approved these changes

2019-09-17 06:20 UTC, KalachevDev commented on tasks/44_time-simulation/time-simulation.js
> +      throw String('Time mustn\'t go backwords');
Backw**a**rds

2019-09-17 06:32 UTC, EasileleM commented on tasks/44_time-simulation/time-simulation.js
> +      throw String('Time mustn\'t go backwords');
Ty xD

2019-09-17 06:35 UTC, merged