Savva Dzhumaliev Tasks 51-60
EasileleM/ui-internship-lwo2 pull request #6
Opened 2019-09-16 13:42 UTC by EasileleM

2019-09-17 07:57 UTC, akimovaa commented on tasks/58_missed-letters/missed-letters.js
> +  return undefined;
function return undefined by default

2019-09-17 08:20 UTC, akimovaa submitted a review, later dismissed

2019-09-17 11:13 UTC, vovcyan requested changes

2019-09-17 11:13 UTC, vovcyan commented on tasks/51_abbreviated-name/abbreviated-name.js
> + * abbreviated - converting full name in
Lets put some example here
Data before transforming and after

2019-09-17 11:13 UTC, vovcyan commented on tasks/52_sum-all-numbers-in-range/sum-all-numbers-in-range.js
> + * sumAll - returns sum of all numbers in given range
Lets put some example

2019-09-17 11:38 UTC, akimovaa submitted a review, later dismissed

2019-09-19 05:22 UTC, savchukm commented on tasks/57_pig-latin/pig-latin.js
> +  const vowels = 'qeuioa';
q is vowel?

2019-09-19 09:55 UTC, akimovaa approved these changes

2019-09-20 15:31 UTC, KalachevDev commented on tasks/51_abbreviated-name/abbreviated-name.js
> +        if (!index) {
A bit confusing

2019-09-20 15:32 UTC, KalachevDev approved these changes

2019-09-20 17:49 UTC, merged