Savva Dzhumaliev Tasks 61-70
EasileleM/ui-internship-lwo2 pull request #7
Opened 2019-09-17 12:39 UTC by EasileleM

2019-09-17 17:08 UTC, vovcyan requested changes

2019-09-17 17:08 UTC, vovcyan commented on tasks/63_insert-string/insert-string.js
> + * insert('We are doing some exercises.')
Bad example

2019-09-17 17:08 UTC, vovcyan commented on tasks/65_smaller-common-multiple/smaller-common-multiple.js
> + * multiple of the provided parameters
What does it mean?

2019-09-17 17:08 UTC, vovcyan commented on tasks/68_drop-elements/drop-elements.js
> + * starting from the front, until the predicate returns true.
Incorrect "starting from the front"

2019-09-17 17:08 UTC, vovcyan commented on tasks/69_unpack-elements/unpack-elements.js
> + * unpackArray - flatten a nested array
Incorrect description

2019-09-17 17:08 UTC, vovcyan commented on tasks/70_binary-decode/binary-decode.js
> + * binaryDecode - return an English translated sentence
Incorrect description

2019-09-19 09:56 UTC, akimovaa approved these changes

2019-09-24 07:22 UTC, vovcyan approved these changes

2019-09-24 07:22 UTC, merged