*feat: tasks 71-80
EasileleM/ui-internship-lwo2 pull request #8
Opened 2019-09-19 06:09 UTC by EasileleM

2019-09-20 11:03 UTC, akimovaa requested changes

2019-09-20 11:03 UTC, akimovaa commented on tasks/72_carrying/carrying.js
> + * addTogether - return sum of two arguments. If only one argument
https://learn.javascript.ru/currying-partials

2019-09-20 11:03 UTC, akimovaa commented on tasks/77_expressions-matter/expressions-matter.js
> +  return Math.max(a + b + c, a * b * c, a + b * c, a * b + c, a * (b + c),
make the code more clear, count the subtotals

2019-09-25 05:18 UTC, alexkond approved these changes

2019-09-25 07:57 UTC, akimovaa approved these changes

2019-09-25 07:58 UTC, merged